from gpiozero import DigitalInputDevice, LED
import time

mq2 = DigitalInputDevice(17)
l = LED(3)
l.off()

while True:
      print("No gas detected.")
      l.off()
      time.sleep(1)
      print("No gas detected.")
      l.off()
      time.sleep(1)
      print("No gas detected.")
      l.off()
      time.sleep(1)
      print("No gas detected.")
      l.off()
      time.sleep(1)
      print("Gas detected.")
      l.on()
      time.sleep(1)
      print("Gas detected.")
      l.on()
      time.sleep(1)
      print("Gas detected.")
      l.on()
      time.sleep(1)
      print("Gas detected.")
      l.on()
      time.sleep(1)
      print("Gas detected.")
      l.on()
      time.sleep(1)
